# Generated by Django 4.2.4 on 2023-08-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/photos/profile/user.png', upload_to='photos/perfil'),
        ),
    ]
